# Generated by Django 3.2.2 on 2022-11-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_course'),
        ('courses', '0007_auto_20221113_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courses_task',
            field=models.ManyToManyField(blank=True, to='task.Task'),
        ),
    ]
