# Generated by Django 3.2.2 on 2022-11-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_course'),
        ('courses', '0008_course_courses_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courses_task',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task.Task'),
        ),
    ]
