# Generated by Django 3.2.2 on 2022-11-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_courses_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_interpreter',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
