# Generated by Django 3.2.2 on 2022-11-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_course'),
        ('courses', '0010_auto_20221114_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courses_task',
            field=models.ManyToManyField(blank=True, to='task.Task'),
        ),
    ]
