# Generated by Django 3.2.2 on 2022-11-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('courses', '0007_auto_20221113_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('courses', models.ManyToManyField(blank=True, to='courses.Course')),
                ('tasks', models.ManyToManyField(blank=True, to='task.Task')),
            ],
        ),
    ]
