# Generated by Django 3.2.2 on 2022-11-14 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20221114_0046'),
        ('task', '0003_remove_task_course'),
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
