# Generated by Django 3.2.2 on 2022-11-15 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_course'),
        ('student', '0002_auto_20221114_0046'),
        ('solution', '0003_auto_20221115_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
