# Generated by Django 3.2.2 on 2022-11-15 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_course'),
        ('solution', '0004_auto_20221115_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='student',
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
