# Generated by Django 3.2.2 on 2022-11-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0007_solution_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='answer',
        ),
    ]
