# Generated by Django 3.2.2 on 2022-11-19 05:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0008_remove_solution_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='result',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
