# Generated by Django 3.2.2 on 2022-11-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='course',
        ),
    ]
