# Generated by Django 3.2.2 on 2022-11-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='instruction',
            field=models.TextField(blank=True),
        ),
    ]
