# Generated by Django 3.2.2 on 2022-11-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
