# Generated by Django 3.2.2 on 2022-11-19 05:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
