# Generated by Django 3.2.2 on 2022-11-19 05:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20221119_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='default_code',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='instruction',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
