# Generated by Django 3.2.2 on 2022-11-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='default_code',
            field=models.TextField(blank=True),
        ),
    ]
