# Generated by Django 3.2.2 on 2022-11-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_file_extension',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
